version: '3.7'
services:
  web:
    build: ./
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    networks:
      - nginx_default
    restart: unless-stopped

networks:
  nginx_default:
    name: nginx_default
