version: '3.7'
services:

  dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '8000:8000'
    networks:
      - nginx_default
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    command: python3 app.py

  prod:
    build: ./
    ports:
      - '8000:8000'
    networks:
      - nginx_default
    restart: unless-stopped

networks:
  nginx_default:
    name: nginx_default
